### ISSUE TITLE
Error in Raster while running replay

### ISSUE THREAD

**Issue by ranitdas2** [JeffersonLab/HallA-APEX-Online#45] opened 2019-02-08 14:51 UTC
Error Message: Warning in <THaRaster("FbusRrb.Raster2")::Decode()>: Number of fired Channels out of range. Setting beam position to nominal values

**Comment by jbane11** [comment] 2019-02-08 14:55
This is caused by the Fast bus Beamline module added by the replay. We no longer have beamline information in Fbus anymore. So I had commented those sections out some time ago. It was commit 66a9014bb1753927b7f1db69773fa7d23ab12b10.  I guess somehow those changes got revert by someone else.

**Comment by jbane11** [comment] 2019-02-08 15:12
Fixed in replay still needs to be adjusted in odef

**Comment by jbane11** [comment] 2019-02-08 15:17
Fixed in odef now, also

**Closed by jbane11** 2019-02-08 15:17 UTC
